language: go

go:
 - 1.12

matrix:
  fast_finish: true

env:
  global:
    - PATH=$HOME/gopath/bin:$PATH

install:
 - go get -t -v ./...
 - go install -a -race std

script:
 - go vet -all .
 - go build ./...
 - go test -race -v ./...
